#include <QtGlobal>
// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *altcoin_strings[] = {
QT_TRANSLATE_NOOP("altcoin-core", ""
"%s, you must set a rpcpassword in the configuration file:\n"
" %s\n"
"It is recommended you use the following random password:\n"
"rpcuser=altcoinrpc\n"
"rpcpassword=%s\n"
"(you do not need to remember this password)\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions.\n"),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Acceptable ciphers (default: TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!AH:!3DES:"
"@STRENGTH)"),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Cannot obtain a lock on data directory %s.  Altcoin is probably already "
"running."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Detach block and address databases. Increases shutdown time (default: 0)"),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Error: The transaction was rejected.  This might happen if some of the coins "
"in your wallet were already spent, such as if you used a copy of wallet.dat "
"and coins were spent in the copy but not marked as spent here."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Error: This transaction requires a transaction fee of at least %s because of "
"its amount, complexity, or use of recently received funds  "),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: "
"86400)"),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Unable to bind to %s on this computer. Altcoin is probably already running."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Warning: -paytxfee is set very high. This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"Warning: Please check that your computer's date and time are correct.  If "
"your clock is wrong Altcoin will not work properly."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"You must set rpcpassword=<password> in the configuration file:\n"
"%s\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions."),
QT_TRANSLATE_NOOP("altcoin-core", ""
"\n"
"SSL options: (see the Altcoin Wiki for SSL setup instructions)"),
QT_TRANSLATE_NOOP("altcoin-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("altcoin-core", "Accept connections from outside (default: 1 if no -proxy or -connect)"),
QT_TRANSLATE_NOOP("altcoin-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("altcoin-core", "Allow DNS lookups for -addnode, -seednode and -connect"),
QT_TRANSLATE_NOOP("altcoin-core", "Allow JSON-RPC connections from specified IP address"),
QT_TRANSLATE_NOOP("altcoin-core", "An error occured while setting up the RPC port %i for listening: %s"),
QT_TRANSLATE_NOOP("altcoin-core", "Bind to given address. Use [host]:port notation for IPv6"),
QT_TRANSLATE_NOOP("altcoin-core", "Altcoin version"),
QT_TRANSLATE_NOOP("altcoin-core", "Altcoin"),
QT_TRANSLATE_NOOP("altcoin-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("altcoin-core", "Cannot initialize keypool"),
QT_TRANSLATE_NOOP("altcoin-core", "Cannot resolve -bind address: '%s'"),
QT_TRANSLATE_NOOP("altcoin-core", "Cannot resolve -externalip address: '%s'"),
QT_TRANSLATE_NOOP("altcoin-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("altcoin-core", "Connect only to the specified node(s)"),
QT_TRANSLATE_NOOP("altcoin-core", "Connect through socks proxy"),
QT_TRANSLATE_NOOP("altcoin-core", "Connect to a node to retrieve peer addresses, and disconnect"),
QT_TRANSLATE_NOOP("altcoin-core", "Discover own IP address (default: 1 when listening and no -externalip)"),
QT_TRANSLATE_NOOP("altcoin-core", "Don't generate coins"),
QT_TRANSLATE_NOOP("altcoin-core", "Done loading"),
QT_TRANSLATE_NOOP("altcoin-core", "Error loading blkindex.dat"),
QT_TRANSLATE_NOOP("altcoin-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("altcoin-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("altcoin-core", "Error loading wallet.dat: Wallet requires newer version of Altcoin"),
QT_TRANSLATE_NOOP("altcoin-core", "Error"),
QT_TRANSLATE_NOOP("altcoin-core", "Error: Transaction creation failed  "),
QT_TRANSLATE_NOOP("altcoin-core", "Error: Wallet locked, unable to create transaction  "),
QT_TRANSLATE_NOOP("altcoin-core", "Error: could not start node"),
QT_TRANSLATE_NOOP("altcoin-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("altcoin-core", "Fee per KB to add to transactions you send"),
QT_TRANSLATE