.TH ALTCOIN.CONF "5" "January 2011" "altcoin.conf 3.19"
.SH NAME
altcoin.conf \- altcoin configuration file
.SH SYNOPSIS
All command-line options (except for '-datadir' and '-conf') may be specified in a configuration file, and all configuration file options may also be specified on the command line. Command-line 